# experiment description
exp_name: 'pedsim'

# environment description
exp_epi_len: 1000

# architecture description
pi_hidden_layers: [256, 256]

# option
# 0-element: batchnorm ('batch-norm' means we use batch normalization)
# 1-element: activation function ('relu', 'leaky-relu', 'sigmoid', 'tanh')
# 2-element: last activation function ('default' means nothing, 'sigmoid', 'tanh')
pi_options: ['default', 'leaky-relu', 'default']


# SAC hyperparameters
replay_size: 4000
gamma: 0.99
polyak: 0.995
lambda: 0.97
cost_alpha: 0.125
max_kl: 0.001
damping_coeff: 0.01
num_conjugate: 10
line_decay: 0.8
cost_d: 0.025

# training hyperparameters
learning_rate: 0.0002
epochs: 2500
steps_per_epoch: 4000
batch_size: 4000
n_log_epi: 10
start_steps: 4000
update_after: 4000
update_every: 4000
save_interval: 10
plot_rendering: True

# seed
seed: 1
